#!/usr/bin/env bash

set -e

CONFIG="dotbot.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# to automatically set the correct TZ (when tzdata is installed)
sudo ln -fs /usr/share/zoneinfo/Poland /etc/localtime
# custom: install core packages
sudo apt-get update
sudo apt-get install -y -qq build-essential python3 curl lsb-release

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
